name    'renanvicente-shellshock'
version '0.0.1'
author  'Renan Vicente'
license 'Apache License Version 2.0'
project_page 'http://www.renanvicente.com'
source  'https://github.com/renanvicente/puppet-shellshock'
summary 'Puppet module for shellshock'
description 'This module determine the vulnerability of a bash binary to the shellshock exploits (CVE-2014-6271 or CVE-2014-7169) and then patch that where possible'
dependency 'puppetlabs/apt', '>= 1.6.0'
